### PR TITLE
Versatile auth URLs & many UI fixes

### LINKED ISSUE #2020: Minor mobile header issues
**Describe the bug**
360px width screen:
image

**To Reproduce**
420px width screen or less has this issue

**How I think this can be fixed**
1) Change [this line](https://github.com/modrinth/knossos/blob/d914b38f9f0288cb3d6800781085c085a935d96e/layouts/default.vue#L238) and [this line](https://github.com/modrinth/knossos/blob/d914b38f9f0288cb3d6800781085c085a935d96e/layouts/default.vue#L263) to 0.5rem
2) If screen is smaller than 450px, hide the `(Beta)` tag; otherwise, leave it be

Result:
image

**Additional context**
I would create a PR for this but I need to sleep, and plus @venashial can add it in their PR as to not cause merge conflicts

Also, I chose 360px because that's the minimum size that Firefox gives in its mobile responsiveness test thing, and thus seems like a good choice for what the minimum "supported" resolution should be

### LINKED ISSUE #2022: Sometimes the green highlight on the tab of a mod page is not there
## Describe the bug
Having query parameters in the URL means that the active tab on mod pages does not show up:
image

## To Reproduce
1. Go to any mod page
3. Append a query parameter to the URL - the way this happens in the wild is when you click login from a mod page and get redirected back. For example: [https://modrinth.com/mod/hydrogen?code=some-login-code](https://modrinth.com/mod/hydrogen?code=some-login-code)
4. Observe that the green line under 'Description' disappears

### Without query parameter
image
### With query param
image

## Expected behavior
The green line should always be visible

### LINKED ISSUE #2024: `Updated` and `Created` contents may occasionally be cut off
here
Should have "ago", not "ag".
Since this is likely going to happen for all `X minutes ago` items, this could probably be easily be fixed by somehow hard-coding it to abbreviate to `X min. ago`, but y'all probably want to do a more elegant solution than that.

### LINKED ISSUE #2026: Alignment of check boxes under /mod/_id/settings is very weird
**Describe the bug**
this monstrosity

**To Reproduce**
At the bottom of /mod/_id/settings, in team member settings.

**Expected behavior**
It shouldn't look that janky.

### LINKED ISSUE #2028: Page 5 button when browsing does not appear when on page 4
**Describe the bug**
Easier to just put a screenshot than to explain it.
image

**To Reproduce**
1. Go to page 4 in search
2. Try to go to page 5 without clicking the next arrow

**Expected behavior**
There should be a `5` button rather than having to press the right arrow

### LINKED ISSUE #2030: Certain elements need more padding/margins on mobile
**Describe the bug**
Some things look too close to the edges on mobile.

**To Reproduce**
Most notable is *everything on the index except the header*, but also appears on mod pages with the summaries.
image
image

**Additional context**
modrinth/knossos#171 may be related with centred footers specifically

### LINKED ISSUE #2032: Clicking "Confirm my choices" creates a smorgasbord of notifications
**Describe the bug**
Clicking on "Confirm my choices" in '/dashboard/privacy' creates a smorgasbord of notifications.

**To Reproduce**
1. Go to '/dashboard/privacy'.
2. Click on 'Confirm my choices' multiple times.

**Expected behavior**
Only one notification should show.

**Additional context**
firefox_tJpxQqOxJP

### LINKED ISSUE #2037: Unfollow button in followed mods section should be right-aligned
this

### LINKED ISSUE #2040: [Bug] Links in Privacy/Terms not formatted
**Describe the bug**
The links in Privacy/Terms not formatted

**To Reproduce**
1. Go to the [privacy](https://modrinth.com/legal/privacy) or [terms](https://modrinth.com/legal/terms) page
2. Find a link
3. Wonder if it's a link until you mouse over it

### LINKED ISSUE #2049: [Bug] No spacing between user profile picture and the report button
Example: 
image

The padding is fine with the bio though

### PR DESCRIPTION
**Pull request by venashial**
Spaces out elements in a `.project-card` using `justify-content: space-between;`.

----
_Edit:_ All linked issues:
Fixes modrinth/code#2037
Fixes modrinth/code#2022
Fixes  modrinth/code#2028
Fixes  modrinth/code#2040
Fixes  modrinth/code#2032
Fixes  modrinth/code#2049
Fixes  modrinth/code#2030
Fixes modrinth/code#2026
Fixes modrinth/code#2054
Fixes modrinth/code#2024
Fixes modrinth/code#2020

### CODE REVIEW

**Comment by Geometrically** [comment]
Could you take a picture of what it looks like now?

**Comment by wafflecoffee** [comment]
Doesn't fix the issue
image

**Comment by venashial** [comment]
This is what it looks like now:

Screenshot_2021-05-08 Followed mods - Modrinth

**Comment by venashial** [comment]
I'm in a local environment and I hard coded some mod IDs to test it.

Logging in kept redirecting me to modrinth.com, and I didn't want to figure out how to get authorization working locally. I probably would have to hard code my token and user ID.

**Comment by wafflecoffee** [comment]
`https://api.modrinth.com/api/v1/auth/init?url=http://localhost:3000`

**Comment by venashial** [comment]
Thanks! That URL (with my port) works but doesn't persist route changes. I ended up changing this bit in middleware/auth.js to get it to work on all pages:

image

**Comment by venashial** [comment]
This pull request also fixes the alignment of the settings button on the "My Mods" page:

image

**Review by triphora — APPROVED** [review]
I am so stupid, I tried running from master branch instead of the patch branch lmao

**Review by Mysterious-Dev — APPROVED** [review]

File: components/layout/MFooter.vue [hunk 1]
```diff
@@ -79,7 +79,7 @@ export default {
 }
 
 footer {
-  padding: 2rem 0 2rem 0;
+  padding: 2rem 1rem;
```
Comment (wafflecoffee) [inline components/layout/MFooter.vue:82]: This causes the footer to be very weirdly aligned on the mods pages, dashboard pages, and any other page that uses a thinner footer, on desktop
image

File: components/layout/ModPage.vue [hunk 2]
```diff
@@ -531,7 +533,18 @@ export default {
...
+
+  .tabs {
+    overflow-x: auto;
+  }
+
+  .settings-tab {
+    margin-left: auto;
+    @media screen and (max-width: 1024px) {
+      margin-left: 0.5rem;
+      padding-right: 2rem;
```
Comment (wafflecoffee) [inline components/layout/ModPage.vue:545]: This is very weird on mobile
image

File: components/layout/ModPage.vue [hunk 3]
```diff
@@ -490,8 +489,11 @@ export default {
   }
   .info {
     @extend %column;
+    padding: 1rem;
+    display: flex;
+    justify-content: flex-start;
```
Comment (wafflecoffee) [inline components/layout/ModPage.vue:494]: image

Comment (wafflecoffee) [reply components/layout/ModPage.vue:494]: It also looks a bit strange on mobile, with the opposite problem:
image
The `Mods > Mod Name > Description` should be centred between that rather large gap and that sort of lack of gap

File: pages/index.vue [hunk 4]
```diff
@@ -385,6 +385,12 @@ export default {
     padding-left: 0 !important;
     text-align: center;
     width: 100%;
+
+    h1,
+    h3,
+    p {
+      padding: 0 5vw;
+    }
```
Comment (wafflecoffee) [inline pages/index.vue:393]: See image for my review of line 315; this also makes everything look like it's going to the left on larger screens

File: pages/legal/terms.vue [hunk 5]
```diff
@@ -201,4 +201,8 @@ export default {
   @extend %card;
   padding: var(--spacing-card-sm) var(--spacing-card-lg);
 }
+
+a {
+  color: var(--color-link);
+}
```
Comment (wafflecoffee) [inline pages/legal/terms.vue:207]: For consistencies sake, could this also be applied to the about page? It has links underlined but without a colour

File: pages/mod/_id/settings.vue [hunk 6]
```diff
@@ -497,12 +497,30 @@ export default {
 
     .main-info {
       margin-bottom: var(--spacing-card-lg);
+
```
Comment (wafflecoffee) [inline pages/mod/_id/settings.vue:500]: NYF but the adding team members thing overflows on mobile
image

File: pages/mods.vue [hunk 7]
```diff
@@ -543,7 +543,7 @@ export default {
         const pageAmount = Math.ceil(res.data.total_hits / res.data.limit)
 
         this.currentPage = newPageNumber
-        if (pageAmount > 4) {
+        if (pageAmount > 3) {
```
Comment (wafflecoffee) [inline pages/mods.vue:546]: image

The first `-` can be replaced with a 2, not sure how hard that'd be to do

**Review by triphora — CHANGES_REQUESTED** [review]
Overall, well done! Mostly just minor nitpicks :)

File: pages/index.vue (hunk 4 above)
Comment (wafflecoffee) [reply pages/index.vue:393]: Oddly enough my comment for said line 315 didn't save, lol. 

It still looks strange on 4k screens, albeit not as strange.
image

**Comment by venashial** [comment]
@wafflecoffee Thanks for the review! I'll fix up the parts needing fixing when I get home.

File: layouts/default.vue [hunk 8]
```diff
@@ -260,7 +292,13 @@ export default {
         display: flex;
         margin-left: auto;
         align-items: center;
-        margin-right: 1rem;
+        margin-right: 0.5rem;
+
+        .theme-toggle {
+          @media screen and (max-width: 375px) {
+            display: none;
+          }
```
Comment (wafflecoffee) [inline layouts/default.vue:300]: If I'm reading this right, you're hiding the theme toggle if the screen is smaller than 375px? Doesn't that defeat the whole purpose of the button, to be able to switch modes from mobile?

Comment (venashial) [reply layouts/default.vue:300]: It does remove the button, which is the easiest way to make the page fit on mobile phones that small. I was using the logic, "If a phone is that small, then lets hope they have a system wide dark mode toggle like an iPhone 5s." But, that might not be true for other older, smaller phones. Also, maybe a user only wants Modrinth to be in dark mode.

Possible solutions?
- Shrink logo
- Get rid of "Modrinth" wording in logo and just use icon
- Shrink buttons (imo not that great of a solution)

Also, semi-unrelated but, wouldn't it be nice to have the mobile navigation on the bottom of the phone?

File: components/layout/MFooter.vue (hunk 1 above)
Comment (venashial) [reply components/layout/MFooter.vue]: My bad, I should have noticed this. I was trying to fix the footer on the index page.

Fixed in aa315876d65c10bc276fe71942e03101481c22a3 using a new prop just for padding.

File: layouts/default.vue (hunk 8 above)
Comment (wafflecoffee) [reply layouts/default.vue:300]: The second image in #203 is at 360px.

Comment (venashial) [reply layouts/default.vue:300]: How did you get that image? 360px looks like this for me (using the changed you suggested):
image

Comment (wafflecoffee) [reply layouts/default.vue:300]: That doesn't *look* like 0.5rem to me, but I could be wrong; the way I did it was adding `style="margin-[left or right]:-0.5rem"` to one of the HTML tags lol  
In that case, switching from logo with text to just logo icon makes the most sense under 375px imo

Comment (venashial) [reply layouts/default.vue]: Everything should be fixed on 8a0a698aa3feca1e8f7ec33bb50aa042de6eb8b3. *This time no dark mode buttons were harmed in the process.*

File: components/layout/ModPage.vue (hunk 2 above)
Comment (venashial) [reply components/layout/ModPage.vue]: Everything should be looking better with 8411e0d40bdd77abfd7768dceb72c1874f459344.

Old:
image

Now:
image

Mobile:
image

File: components/layout/ModPage.vue [hunk 9]
```diff
@@ -465,6 +467,14 @@ export default {
...
       this.userFollows.splice(this.userFollows.indexOf(this.mod.id), 1)
     },
+    formatTime(date) {
+      date = '2021-05-10T03:24:42.106423Z'
+      let defaultMessage = this.$dayjs(date).fromNow()
+      if (defaultMessage.length > 13) {
+        defaultMessage = defaultMessage.replace('minutes', 'min.')
+      }
+      return defaultMessage
+    },
```
Comment (wafflecoffee) [inline components/layout/ModPage.vue:477]: No mods were updated recently enough at the time of writing to test this, but, I'm going to assume it works :+1:

**Review by triphora — APPROVED** [review]

**Comment by Mysterious-Dev** [comment]
Fabric API is update recently.

**Comment by wafflecoffee** [comment]
> Fabric API is update recently. 

Not any within the last hour

**Comment by wafflecoffee** [comment]
Oh. Something's broken then
image

**Comment by Redblueflame** [comment]
It is maybe caused by the hardcoded date

**Comment by venashial** [comment]
Whoops, I forgot to get rid of the hardcoded date I was using to fix modrinth/knossos#193. I'm glad you all caught that.

File: pages/mods.vue (hunk 7 above)
Comment (venashial) [reply pages/mods.vue]: Should be all fixed

File: pages/legal/terms.vue (hunk 5 above)
Comment (venashial) [reply pages/legal/terms.vue:207]: Added in ac33cc730d93aa5b5a75d69bc2288aa5ef40590d

File: pages/index.vue (hunk 4 above)
Comment (venashial) [reply pages/index.vue:407]: Everything should look better on 4k screens after aed1a2c

**Review by Redblueflame — APPROVED** [review]
That was quite a big PR, in the future please make multiple smaller ones.
But all in all, looks good to me, thanks for your contribution 👍

**Comment by venashial** [comment]
You are totally right, this PR just grew and grew. I wasn't sure if the lack of merge conflicts would outweigh the mess of it all.

**Comment by venashial** [comment]
I don't think this should be merged yet. There are issues with the sign-in button being given a broken URL (a localhost one) when rendered server-side with Heroku. The server doesn't have a way of knowing the page domain. I think this should be fixed by having some variable for the page domain (maybe in the vuex store) that is either localhost:port when in development or a set value in production.

**Comment by venashial** [comment]
Still not working, something to do with NODE_ENV I think.

**Comment by venashial** [comment]
Seems to work locally and on Heroku & Vercel now. I'll just remove the console.log() now.

**Comment by venashial** [comment]
The Vercel page: https://knossos-preview-7ercbw7ft-venashial.vercel.app/

**Comment by venashial** [comment]
Small note: The URL is automatically picked using Heroku env variables that are only injected in pull request preview deployments. That's why there is still a fallback to `'https://modrinth.com'`. If [dyno metadata](https://devcenter.heroku.com/articles/dyno-metadata) was enabled, it wouldn't be needed.

**Review by triphora — APPROVED** [review]
Awesome, couldn't find any issues in my testing :)

File: assets/images/utils/settings.svg [hunk 10]
```diff
@@ -0,0 +1 @@
+<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>
```
Comment (falseresync) [inline assets/images/utils/settings.svg:1]: Use this to optimize https://jakearchibald.github.io/svgomg/

File: components/ui/ProjectCard.vue [hunk 11]
```diff
@@ -40,7 +41,7 @@
                   >Draft</span
                 >
                 <span v-if="status === 'processing'" class="badge yellow">
-                  Processing
+                  Processing/Under Review
```
Comment (falseresync) [inline components/ui/ProjectCard.vue:44]: An `or` is more visually appealing. Additionally, try not to use Pascal Case. It is out of style, plus just a tiny bit harmful to accessibility if used too much

File: layouts/default.vue [hunk 12]
```diff
@@ -230,19 +259,36 @@ export default {
...
         align-items: center;
         display: flex;
         justify-content: space-between;
         padding: 1rem 0;
         margin-left: 1rem;
         color: var(--color-text-dark);
+        .small-logo {
+          display: none;
+        }
+        @media screen and (max-width: 350px) {
```
Comment (falseresync) [inline layouts/default.vue:275]: No max-width, be mobile-first: use min-width

File: pages/dashboard.vue [hunk 13]
```diff
@@ -78,7 +78,9 @@ export default {
   },
   computed: {
     authUrl() {
-      return `https://api.modrinth.com/api/v1/auth/init?url=https://modrinth.com${this.$route.fullPath}`
+      return `https://api.modrinth.com/api/v1/auth/init?url=${
+        process.env.domain || window.location.origin
```
Comment (falseresync) [inline pages/dashboard.vue:82]: Are you sure this is right logic here? Perhaps null coalescing operator is better (?? operator). || operator will default to the right hand side on any falsey value, including `''` and `0`, while ?? operator will only do so on `null` or `undefined` value

**Review by falseresync — CHANGES_REQUESTED** [review]

File: components/ui/ProjectCard.vue (hunk 11 above)
Comment (venashial) [reply components/ui/ProjectCard.vue:44]: I can use an `or`, it just makes the already large badge larger. I like having `Review` capitalized, but I'll change it.

File: pages/dashboard.vue (hunk 13 above)
Comment (venashial) [reply pages/dashboard.vue:82]: It doesn't really matter, because `process.env.domain` would never be `''` or `0`. Though, maybe it isn't even needed. [This](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-env/) makes it sound like environment variables are available client side.

File: components/ui/ProjectCard.vue (hunk 11 above)
Comment (venashial) [reply components/ui/ProjectCard.vue:44]: Neither `or` nor Sentence case look more visually appealing to me after trying them.

Which of the options below do you like the most? Or did you have something else in mind?

\#&#x2060;1
image
\#&#x2060;2
image
\#&#x2060;3
image
\#&#x2060;4
image
\#&#x2060;5
image

Personally, I like #&#x2060;6. #&#x2060;3 is okay too.

Comment (wafflecoffee) [reply components/ui/ProjectCard.vue:44]: Personally, I'd just prefer `Under review`, no need to even have `Processing` there imo, but false may have something else in mind

**Comment by venashial** [comment]
Updated Vercel deployment: https://knossos-preview-ng7yipbx0-venashial.vercel.app/

File: pages/dashboard.vue (hunk 13 above)
Comment (venashial) [reply pages/dashboard.vue]: Turns out `window.location.origin` isn't needed. I removed it in b44fdc0.

File: layouts/default.vue (hunk 12 above)
Comment (venashial) [reply layouts/default.vue]: Fixed with fa1e60c

File: assets/images/utils/settings.svg (hunk 10 above)
Comment (venashial) [reply assets/images/utils/settings.svg]: Done in a1c9a5c

**Comment by Mysterious-Dev** [comment]
It's a good work.

**Comment by venashial** [comment]
Everything is finally merged with upstream correctly.

**Comment by Mysterious-Dev** [comment]
@falseresync review ?

File: components/ui/ProjectCard.vue (hunk 11 above)
Comment (Minenash) [reply components/ui/ProjectCard.vue:44]: If I remember correctly, the Processing was for when Modrinth checked files automatically, but seeing that doesn't exist yet, won't be a thing for a while, and should probably have it's own status, I agree it should just be `Under review`

Comment (venashial) [reply components/ui/ProjectCard.vue:44]: I agree, `Under review` makes the most sense currently. If/when the backend starts processing files, this will be easy to change.

**Comment by WickedTree** [comment]
Dunno if this should be put in its own PR, but alignment for the version list is kind of funky: 
image
especially the mod loader and status columns.
Maybe just center everything?
there also isn't enough space between "date published" and the edge

**Comment by venashial** [comment]
> Dunno if this should be put in its own PR, but alignment for the version list is kind of funky:

@WickedTree 

Probably could be its own PR, related to #219.
