### PR TITLE
Miscellaneous fixes relating to statuses, et al

### LINKED ISSUE #915: Moderation status card phrasing
### Describe the bug

The moderation status card button says "Resubmit for review" even when a project has not yet been submitted.
image
The button could also be greyed out until the project is eligible to submit (Such as including a version)

### Steps to reproduce

1. Create a new draft
2. Check the moderation status card 

### Expected behavior

The button to initially say "Submit for review" like on the project checklist, and then "Resubmit for review" once a project has been rejected for whatever reason

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by triphora**
Fixes #915

### CODE REVIEW

File: components/ui/ProjectPublishingChecklist.vue [hunk 1]
```diff
@@ -290,17 +308,27 @@ export default {
           },
         },
         {
-          condition: this.project.status === 'draft',
-          title: 'Submit for review',
+          condition: true, // This condition is handled for us in the root div
+          title: `${
```
Comment (Prospector) [inline components/ui/ProjectPublishingChecklist.vue:312]: Think this may have been a bit more readable if it was implemented as two separate nags with `hide` conditions

**Review by Prospector — APPROVED** [review]
