### PR TITLE
Fix serverless crash + Version Filters on reload

### LINKED ISSUE #1047: Project version filters in URL do not apply
### Describe the bug

When filters for a project are set via a URL (the `?l=...&g=...&c=...` in i.e. `modrinth.com/mod/fabric-api/versions?g=1.19.3&c=release`), they will populate in the UI options but not actually perform a search.

image

Additionally, modifying the filter with the UI options proves unsuccessful until you completely clear the filters (either manually or with the Clear Filters button) and then try again

### Steps to reproduce

1. Go to https://modrinth.com/mod/fabric-api/versions
2. Select a filter
3. Refresh the page
4. Note that your filter has been lost despite its presence in the URL and the UI seemingly indicating that your filter has been applied. Also note that no matter what you do to the filter, it will not apply (neither to the page or the URL) until you clear all of the options (manually or with the Clear Filters button)

### Expected behavior

Page should display only the appropriate filtered versions to allow developers to share links to the latest builds of their mod for specific platforms or game versions

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Geometrically**
Fixes #1047

### CODE REVIEW

File: pages/[type]/[id]/versions.vue [hunk 1]
```diff
@@ -161,15 +153,32 @@ const metaDescription = computed(
 
 const route = useRoute()
 const currentPage = ref(Number(route.query.p ?? 1))
-const filteredVersions = shallowRef(props.versions)
+const filteredVersions = computed(() => {
```
Comment (Prospector) [inline pages/[type]/[id]/versions.vue:156]: only comment is this looks like a sizable chunk of duplicated code

**Review by Prospector — APPROVED** [review]

File: pages/[type]/[id]/versions.vue (hunk 1 above)
Comment (Geometrically) [reply pages/[type]/[id]/versions.vue:156]: yeah I think we can fix this in the future, but it felt weird putting it in utils for such a specific feature
