### PR TITLE
Continue the cleanup train

### LINKED ISSUE #393: Too much padding on the donation link area.
### Environment

Website

### Describe the bug

On the "Donation Links" section, there happens to be too much padding.

### Steps To Reproduce

1. Go to your project
2. Go to project settings -> edit
3. Scroll all the way to the donation link section

### Expected behavior

Not as much padding.

### Additional context

too much padding

### LINKED ISSUE #394: Wonky dropdowns in search section
### Environment

Website

### Describe the bug

The rounding on the dropdown when "dropping upwards" is a lot less than what the rounding is when the dropdown is dropping down.

### Steps To Reproduce

1. Go to the mods page
2. Navigate to the Versions and License dropdowns
3. Use the dropdowns

### Expected behavior

Consistent rounding basically.

### Additional context

inconsistent rounding

### PR DESCRIPTION
**Pull request by Prospector**
I know some of the media queries look a bit insane but trust me it works lol

Closes #394
Closes #393

### CODE REVIEW

File: pages/search.vue [hunk 1]
```diff
@@ -584,57 +586,93 @@ export default {
...
 
 .no-results {
   text-align: center;
 }
 
-@media (min-width: 1024px) {
-  .sidebar-menu {
-    display: block;
-    margin-top: 0;
+@media (min-width: 700px) {
```
Comment (wafflecoffee) [inline pages/search.vue:636]:
```suggestion
@media (min-width: 850px) {
```
Between 700 and 850px, the per-page kind of glitches out

**Review by wafflecoffee — APPROVED** [review]
LGTM besides the one thing

**Review by wafflecoffee — APPROVED** [review]
